<?php

namespace AppBundle\Repository;

/**
 * PodometerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PodometerRepository extends \Doctrine\ORM\EntityRepository
{
    public function sumAll(){
        $sql = 'SELECT SUM(value) FROM podometer';

        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();
        $res = $statement->fetchAll();
        return $res[0]["SUM(value)"];
    }

    public function sumAllMonth(){
        $d = new \DateTime();
        $sql = "SELECT SUM(value) FROM podometer where date >= '".$d->format('Y-m')."-01'";

        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();
        $res = $statement->fetchAll();
        $res2 = $res[0]["SUM(value)"];
        if($res2){
            return $res2;
        } else {
            return 0;
        }
    }

    public function sumAllDay(){
        $d = new \DateTime();
        $sql = "SELECT SUM(value) FROM podometer where date >= '".$d->format('Y-m-d')."'";

        $em = $this->getEntityManager();
        $connection = $em->getConnection();
        $statement = $connection->prepare($sql);
        $statement->execute();
        $res = $statement->fetchAll();
        $res2 = $res[0]["SUM(value)"];
        if($res2){
            return $res2;
        } else {
            return 0;
        }
    }

    public function getLast5(){
        $query = $this->createQueryBuilder('p')
            ->orderBY('p.date')
            ->setMaxResults(5)
            ->getQuery();

        return $query->getResult();
    }

    public function getAll(){
        $query = $this->createQueryBuilder('p')
            ->orderBY('p.date')
            ->getQuery();

        return $query->getResult();
    }
}
